<?php

const USERPOST = 1;
const EXCLUSIVEPOST = 2;
const COMMUNITYPOST = 3;
const EXCLUSIVECOMMINITYPOST = 4;
const ANNOUNCEMENTPOST = 5;
const PORTFOLIOPOST = 6;

const PUBLICCOMMUNITY = 1;
const PRIVATECOMMUNITY = 2;